I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 193, in script
    $ pointG += 1
  File "game/script.rpy", line 193, in <module>
    $ pointG += 1
NameError: name 'point' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 193, in script
    $ pointG += 1
  File "C:\Users\Вовчик\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Вовчик\Desktop\renpy-8.3.4-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 193, in <module>
    $ pointG += 1
NameError: name 'point' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
BSTU 1.0
Fri Jan  3 22:36:19 2025
